### ISSUE TITLE
Reorganize model hierarchy

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-tunisia#10]
Something similar to [openfisca-france hierarchy](https://github.com/openfisca/openfisca-france/tree/master/openfisca_france/model) would be convenient.

**Comment by benjello** [comment]
Some work have been done but still to be finished. The file `model/data.py` should be entirely dispatched accross other files. Variables should be renamed to longer names.

**Comment by sandcha** [comment]
@benjello Pour prochain milestone ou au-delà ?

**Comment by benjello** [comment]
Ok for next milestone

**Comment by benjello** [comment]
Almost done:
 - [ ] refine variables socio-démographiques (education, handicap)
 - [ ] clean revenus d'activite non-salaries

**Comment by benjello** [comment]
Superseded by #112
