### ISSUE TITLE
Compléter les labels

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-tunisia#12]
- [ ] En français: 
  - [ ] [revenus fonciers](https://github.com/openfisca/openfisca-tunisia/blob/master/openfisca_tunisia/model/revenus.py#L269-L323)   
  - [ ] [BIC, etc](https://doc.openfisca.fr/en/contribute/commit-messages.html)

en utilisant [la déclaration](https://github.com/openfisca/openfisca-tunisia/blob/master/openfisca_tunisia/doc/dec_irpp_fr.pdf) (si possible en profiter pour adopter des noms long, voir aussi #10, en suivant les recommendations exprimées [ici](https://doc.openfisca.fr/en/contribute/variables-naming.html) et [là](https://doc.openfisca.fr/en/contribute/commit-messages.html))
  
- [ ] Traduire les labels en arabe

**Comment by benjello** [comment]
@cbenz : pourrais-tu nous lister les fichiers à manipuler pour traduire un maximum de choses en arabe (UI, legislation explorer compris) ? Merci d'avance.

**Comment by cbenz** [comment]
Pour l'UI c'est là : 
https://github.com/openfisca/openfisca-web-ui/tree/master/openfisca_web_ui/static/i18n

Pour legislation explorer ce n'est pas fait, c'est en français en dur.

Pour le site web c'est plus complexe :
– les traductions de certaines chaînes : 
https://github.com/openfisca/openfisca-web-site/tree/master/openfisca_web_site/i18n
– les pages éditoriales (page d'accueil, news) : 
https://github.com/openfisca/openfisca-web-site/tree/master/openfisca_web_site/templates/tunisia
– les blocs de contenu (les outils) : 
https://github.com/openfisca/openfisca-web-site/blob/master/openfisca_web_site/templates/france/fr/tree/elements/index.py 
(à dupliquer dans un répertoire tunisia, il faut que je regarde)


-- 
Christophe Benz
Développeur à Etalab, Services du Premier Ministre
Tour Mirabeau, 39-43 quai André Citroën, 75015 Paris
christophe.benz@data.gouv.fr / +33 1 40 15 68 91 / http://openfisca.fr

**Comment by benjello** [comment]
@ChemaTr @sabeura: il faut comparer le fichier [ar.json](https://github.com/openfisca/openfisca-web-ui/blob/master/openfisca_web_ui/static/i18n/ar.json) avec la version [française](https://github.com/openfisca/openfisca-web-ui/blob/master/openfisca_web_ui/static/i18n/fr.json) ou [anglaise](https://github.com/openfisca/openfisca-web-ui/blob/master/openfisca_web_ui/static/i18n/en.json) pour remlacer les champs non traduits.

Vous pouvez tout faire en ligne. Faites un essai en traduisant un seul terme pour voir si vous arrivez à soumettre vos changements.

**Comment by benjello** [comment]
Merci @sabeura: ton tarvail a bien été soumis ici https://github.com/openfisca/openfisca-web-ui/commit/a0c8fa732bca91724160024a5ebeb6a839a85065 .

**Comment by benjello** [comment]
A conslider avec #21

**Comment by benjello** [comment]
@sandcha : je te laisse consolider tout ce qui est label/reference multilingue ?
Bounce back si tu n'es pas partante.

**Comment by benjello** [comment]
Obsolète
