### ISSUE TITLE
Expliciter les différences entre le Smig 40h et le Smig 48h dans le wiki ?

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-tunisia#13]
Est-ce vraiment une différence sur le temps de travail ?
Quand le Smig est mentionné dans la législation, lequel doit-on considérer ?

**Comment by sandcha** [comment]
Code du travail, Chapitre VI - Durée du travail , [Section I - Régime normal](http://www.legislation.tn/fr/affich-code-article/code-du-travail-article-79-%28modifié-par-la-loi-n°96-62-du-15-juillet-1996%29__10430).

**Comment by sandcha** [comment]
Connected to #64 

Imho, lorsque le SMIG est évoqué dans la législation, le texte concerne à la fois les régimes 40h et 48h. 
Même s'il demeure possible qu'on déduise un régime d'un texte sur une catégorie salarié particulière, je propose de clôturer cette issue en attendant la réidentification d'un cas concret. @benjello ?

**Comment by benjello** [comment]
@sandcha d'accord, je ferme.
