### ISSUE TITLE
Créer les tests pour l'application du barème

### ISSUE THREAD

**Issue by trojette** [openfisca/openfisca-tunisia#15]

**Comment by benjello** [comment]
Cela se passe [ici](https://github.com/openfisca/openfisca-tunisia/tree/master/openfisca_tunisia/tests/formulas)
@trojette tu peux le faire en ligne, cela créera automatiquement un pull-request et lancera les tests sur travis. Je t'encourage à en faire un pour tester le processus rapidemet. On aura du faire cela hier.

**Comment by benjello** [comment]
J'ai corrigé les problèmes de syntaxe (il faut des espaces après les : en yaml) et les erreurs qui provenaient des séries tronquées de paramètres. J'ai aussi changer l'année 2017 à 2016 car le nouveau barème n'est pas encore en vigueur. Je l'ai cependant créer comme une réforme et je vais essayer de rapidement mettre en place le test de cette réforme.

J'ai essayé d'ignorer les tests qui foirent avant de les transférer mais visiblement le champ ignore n'est pas pris en compte. Any hint @cbenz ?

**Comment by trojette** [comment]
Où est-ce que je peux voir le résultat des tests ?

**Comment by benjello** [comment]
Les résultats des tests sont [là](https://travis-ci.org/openfisca/openfisca-tunisia).
Les tests du plf_2017 sont à mettre [ici](https://github.com/openfisca/openfisca-tunisia/tree/master/openfisca_tunisia/tests/reforms/plf_2017)

**Comment by benjello** [comment]
@cbenz : problem solved (but i do not know what was the cause

**Comment by benjello** [comment]
obsolète
