### ISSUE TITLE
Faire le sketch de l'écran d'accueil

### ISSUE THREAD

**Issue by trojette** [openfisca/openfisca-tunisia#16]

**Comment by sandcha** [comment]
@ChemaTr Ecran d'accueil de l'application OGP, n'est-ce pas ?

**Comment by ChemaTr** [comment]
oui

**Comment by sandcha** [comment]
Merci. Action terminée donc. 
Les futurs demandes d'évolution à ce sujet pourront être exprimées sur le repo de l'application client.
