### ISSUE TITLE
SMIG 48H horaire

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-tunisia#23]
En comparant deux sources, il apparaît des différences: 
  - Sur la période 2003-07-01 / 2004-06-30, quelle est la bonne valeur: 1,015 ou 1,014 TND ?
  - La valeur du SMIG à 1,211 TND débute-t-elle le 2008-06-01 ou 2008-07-01 (pour finir le 2009-07-31) ?

**Comment by sandcha** [comment]
> Sur la période 2003-07-01 / 2004-06-30, quelle est la bonne valeur: 1,015 ou 1,014 TND ?

1,015 d'après cette [liste du Ministère des Affaires Sociales](http://www.social.tn/fileadmin/user1/doc/pdftravail/evosmig48FR.pdf) ([sauvegarde](https://drive.google.com/file/d/10McFT4xBzmYDbQRxkLzuW4ySpD6ET_DH/view?usp=sharing)).

> La valeur du SMIG à 1,211 TND débute-t-elle le 2008-06-01 ou 2008-07-01 (pour finir le 2009-07-31) ?

Le 01/07/2008 d'après [le Décret n°2008-2072 du 02 Juin 2008, Art 8](http://www.legislation.tn/sites/default/files/fraction-journal-officiel/2008/2008F/046/TF200820723.pdf).
