### ISSUE TITLE
Corriger séries SMIG/SMAG

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-tunisia#24]
Il manque les séries longues (avant 1990) des SMIG mensuel 40h et 48h.

**Comment by sandcha** [comment]
@benjello Une piste (cf. page 105 numérique/103 papier) : [Rapport OCDE - Investir dans la jeunesse en Tunisie](http://www.oecd.org/fr/pays/tunisie/investir-dans-la-jeunesse-en-tunisie-9789264228290-fr.htm)
Est-ce trop loin de la source ?

**Comment by sandcha** [comment]
@zoubak Il s'agit de compléter le fichier SMIG-40-48.xlsx [ici](https://github.com/openfisca/openfisca-tunisia/tree/master/openfisca_tunisia/assets) en conservant la même structure parce qu'il est lu par le script du même répertoire mais en ajoutant la source de ces données.

**Comment by sandcha** [comment]
Références vers les décrets de 2003 à 2011 environ sur [jurisitetunisie.com](https://www.jurisitetunisie.com/tunisie/index/SMIG.htm) (cf. "Note").

**Comment by sandcha** [comment]
Documents à la source d'`assets/SMIG-40-48.xlsx` : pdf [SMIG 40h](http://www.social.tn/fileadmin/user1/doc/pdftravail/evosmig40FR.pdf) et [SMIG 48h](http://www.social.tn/fileadmin/user1/doc/pdftravail/evosmig48FR.pdf) du [Ministère des Affaires Sociales](http://www.social.tn/index.php?id=48&L=0)

**Comment by sandcha** [comment]
> En plus du SMAG, il existe une `prime de technicité` journalière qui diffère entre ouvrier spécialisé et ouvrier qualifié. Exemple : [Décret n°2017--669](http://www.legislation.tn/sites/default/files/fraction-journal-officiel/2017/2017F/045/Tf20176693.pdf)

**Comment by benjello** [comment]
@sandcha : pourrais-tu vérifier que tout a été transféré dans les YAML et on ferme.
Merci !

**Comment by benjello** [comment]
Done
