### ISSUE TITLE
Salaire de référence

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-tunisia#3]
Fix salaire de référence for tunisa_pension @hmongi @barouni

**Comment by benjello** [comment]
C'est pour le calcul des retraites en focntio nde la carrière: hors de la prochaine milestone.

**Comment by sandcha** [comment]
@benjello IRPP > catégories de revenus soumis à l'IRPP > pensions de retraites, non ? Si ce n'est pas de l'IRPP pour toi, dans quelle future fonction classes-tu ça ?

**Comment by benjello** [comment]
C'est pour openfisca-tunisia-pension, un moteur de calcul de ta retraite en fonction de ta carrière.
Ici on suppose que les gens remplisse leur feuille d'impôt et indique le montant de pension sur la déclaration.

**Comment by benjello** [comment]
Plus le bon repo  openfisca/openfisca-tunisia-pension
