### ISSUE TITLE
Corriger les références à i18n.

### ISSUE THREAD

**Issue by sandcha** [openfisca/openfisca-tunisia#35]
Les fichiers [setup.py](https://github.com/openfisca/openfisca-tunisia/blob/9ebfc27aa9031a44dd16b1fffb61d1f0aa954657/setup.py#L35-L36) et [setup.cfg](https://github.com/openfisca/openfisca-tunisia/blob/9ebfc27aa9031a44dd16b1fffb61d1f0aa954657/setup.cfg) font aujourd'hui référence à un répertoire `i18n/`qui n'existe plus.
Faut-il corriger ces fichiers ou restituer le répertoire ?

Cela pose la question de la gestion du multilinguisme : Avons-nous besoin de traduction arabe des termes au-delà des questions d'IHM ? 
Pour les labels, il me semble que oui parce que même au niveau du code, il pourrait être utile de maintenir une base de correspondance entre les mots métier FR/AR. Mais où et comment ? 
Ceci est en lien avec la résolution de #21 et de #12.

Cette question peut aussi affecter les messages d'erreurs et autres warnings. 
Comment est-ce géré aujourd'hui ?

Plus largement, côté France, l'avenir d'un tel répertoire semble compromis : https://github.com/openfisca/openfisca-france/issues/737

**Comment by benjello** [comment]
Le but est de gérer la traduction FR/AR dans openfisca.
Mais on n'a pas vraiment avancé.

Pour les messages d'erreur etc, je suis pour que l'on laisse tout ce qui est lié à core en anglais jusqu'à
preuve d'une demande de les voir traduits.

**Comment by sandcha** [comment]
@benjello Justement, l'idée était de débuter la chose parce que ce serait plus simple de le faire à mesure. Traduire à minima les labels concernés par #21, je m'en charge si je sais où les inscrire. 

@cbenz Est-ce qu'il y a une autre solution technique que les .po gettext que tu préconiserais pour les traductions ?

A ce stade, je ne vois que deux consommations possibles de ces traductions : 
- Le développeur qui cherche à lier une source officielle en arabe et le code.
- Le legislation explorer qui présenterait les définitions de variables en arabe.
Est-ce qu'il y en a d'autres ?

**Comment by benjello** [comment]
@sandcha : je suis d'accord il faut le faire au fur et à mesure et à défaut être en mesure de lister les traductions manquantes.

Tu as bien identifié les besoins. On peut rajouter toute application qui utilise les labels des variables.

**Comment by MattiSG** [comment]
> Le legislation explorer qui présenterait les définitions de variables en arabe.

Pour information, nous [recommandons](https://doc.openfisca.fr/contribute/language.html) de tout documenter dans la langue du pays modélisé : nous doutons que des expert·e·s de la législation du pays qui souhaiteraient contribuer, ou des citoyen·ne·s, ne soient pas à l'aise avec la langue du pays en question. Inversement, ce même public peut être rebuté par des commentaires en anglais. Il y a également un risque de désynchronisation entre les deux langues, et se poserait la question : laquelle ferait foi ?

**Comment by benjello** [comment]
En Tunisie, les formulaires sont dans les deux langues et le public n'est pas homogène. Certains sont plus à l'aise en arabe qu'en français et vice-versa. Se pose aussi le problème de l'alphabet. Le nom des variables donc en français. Donc il serait bien de garder la description en français mais également de pouvoir disposer de la traduction en arabe.

**Comment by benjello** [comment]
@sandcha : je ferme mais si le coeur t'en dit je verrais bien une gestion bilingue des références tant pour les paramètres que pour les variables. En effet, nous disposons désormais de deux bonnes sources dans les deux langues:
  - [Le portail du ministère des finances](https://doc-fiscale.finances.gov.tn/cimf-internet/page/doc-portal/fr/#path=%2F)
  - [Le site de référence de la législation tunisienne](www.legislation.tn)  
 
On peut commencer par quelque chose de frustre mais qui sera facilement convertible par la suite.
Je te laisse fermer cette issue et en ouvrir une autre avec des propositions concrètes.
Une fois notre stratégie arrêtée, on se fait un plan de référencement et on s'y colle au rythme que l'on peut tenir.

Qu'en dis-tu ?

**Comment by benjello** [comment]
Cette issue est liée à #54.

**Comment by benjello** [comment]
Obsolète
