### ISSUE TITLE
Compléter référence législatives

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-tunisia#42]
Compléter les références législatives des régimes sociaux en s'aidant de la doc recensée dans le wiki en complétant le champ référence dans le fichiers de paramètres

**Comment by sandcha** [comment]
Input intéressant ? : [textes législatifs de la CNSS](http://www.cnss.tn/web/guest/telecharger/-/document_library_display/9MhK/view/20609)

**Comment by benjello** [comment]
Oui ! Mais il faut trouver un moyen de sauvegarder les documents car je ne parierai pas sur la pérennité des sites web d'origine

**Comment by sandcha** [comment]
2 des 3 documents ont pu être téléchargés. Ils sont maintenant disponibles sur un drive public :
[Accients de travail et maladies professionnelles.pdf](https://drive.google.com/file/d/1GBWqEzhMb6FSgGBPgNcGUAH5lzKS8sPc/view?usp=sharing) 
[Salariés agricoles Indépendants et autres catégories.pdf](https://drive.google.com/file/d/1QmwGI72-5HG6_KGRhU_NYryiYzK4YqNt/view?usp=sharing)

**Comment by benjello** [comment]
Voir si on ne peut pas trouver des références plus pérennes dans www.legislation.tn ou sur le site du ministère des finances.

Je mets cela dans ta besace @sandcha (doc et i18n).
Renvoie l'ascenseur si pas intéressée.

**Comment by benjello** [comment]
Obsolète
