### ISSUE TITLE
Références législatives pour les évolutions des barèmes

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-tunisia#54]
> Concerne openfisca_tunisia/parameters/impot_revenu/bareme.yaml
> La contribution sociale solidaire ci-dessous est associée à ce barème d'où le questionnement sur la référence législative à indiquer.
---
Pour la CSG introduite en 2018:
مساهمة اجتماعية تضامنية لفائدة الصناديق الاجتماعية,
ceci est évoqué par الفصل 53 de la Loi de Finance 2018 (page 4287).

@sandcha : je ne sais pas comment mettre des références dans un barème !

**Comment by sandcha** [comment]
@benjello Voici un [exemple openfisca-france](https://github.com/openfisca/openfisca-france/blob/b1a7cc31508f396a4cb088198cab9019b7fe71b3/openfisca_france/parameters/cotsoc/pat/commun/chomfg.yaml)

Si on reprend le barème à l'origine de cette discussion `impot_revenu/bareme.yaml`, ces quatre syntaxes sont possibles et la documentation n'en favorise a priori pas : 
```
description: Tranches de l'IR
reference:
  Article 53 de la loi no 2017-66 du 18-12-2017 portant Loi de finances 2018 
  2018-01-01: Article 53 de la loi no 2017-66 du 18-12-2017 portant Loi de finances 2018

brackets:
- rate:
    1990-01-01:
      value: 0
    2017-01-01:
      value: 0
    2018-01-01:
      value: 0.01
      reference: Article 53 de la loi no 2017-66 du 18-12-2017 portant Loi de finances 2018
  threshold:
    1990-01-01:
      value: 0
    2017-01-01:
      value: 0
    2018-01-01:
      value: 0
      reference: Article 53 de la loi no 2017-66 du 18-12-2017 portant Loi de finances 2018
```
La première, est de format libre ; elle pourrait être préfixée par autre chose ou rien mais il me semble que la date serait pratique.
Je serais pour mettre la référence au plus près de la valeur quand elle en impacte peu.
A priori, legislation explorer ne traite pas encore des références pour les paramètres.

**Comment by sandcha** [comment]
Que faut-il pour traiter cette issue ? : Ajouter les informations concernant la "CSG" ? Les ajouter dans un nouveau fichier d'un nouveau répertoire `parameters/prelevements_sociaux/contributions/...` ?

**Comment by benjello** [comment]
Cette CSG est est 1% et je l'ai intégrée au barème. Je ne sais pas s'il faut la séparer du barème pour l'instant. Par contre ce serait bien de mettre les références pour les changements de barème.

**Comment by sandcha** [comment]
> Mémo :  Barème accessible sur legislation.tn dans les `codes en vigueur`> `code de l'irpp` et, pour 2019, [Section III - Taux et barème de l'impôt, article 44](http://www.legislation.tn/fr/affich-code-article/code-de-l%2526%2523039%3Bimpôt-sur-le-revenu-des-personnes-physiques-et-de-l%2526%2523039%3Bimpôt-sur-les-sociétés-article-44-__6177).

**Comment by benjello** [comment]
Obsolète
