### ISSUE TITLE
flake8: error: no such option: --first

### ISSUE THREAD

**Issue by trojette** [openfisca/openfisca-tunisia#7]
See https://travis-ci.org/benjello/openfisca-tunisia/builds/172780785

**Comment by cbenz** [comment]
OK, this is an old error that was fixed in OpenFisca-France but I did not apply the fix to Tunisia. I'm doing it right now.

**Comment by cbenz** [comment]
see bfe2c215cb1b3d4ee4d4148960cd91ac0c6e14a4
